In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\rokha\anaconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\rokha\anaconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\rokha\anaconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
data_yelp = pd.read_csv("yelp_labelled.txt", sep ='\t', header=None)

In [3]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [4]:
col_name = ['Review', 'Sentiment']
data_yelp.columns = col_name

In [5]:
data_amazon = pd.read_csv('amazon_cells_labelled.txt', sep='\t', header=None)

In [6]:
data_amazon.columns = col_name

In [7]:
data_imdb = pd.read_csv('imdb_labelled.txt', sep='\t', header=None)

In [8]:
data_imdb.columns = col_name

In [9]:
data = pd.concat([data_yelp, data_amazon, data_imdb], ignore_index=True)

# Check the first few rows of the concatenated DataFrame
print(data.head())


                                              Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1


In [10]:
x = data['Review']
y = data['Sentiment']

In [11]:
import string
import nltk
import spacy
# Download the spaCy model
!python -m spacy download en_core_web_sm

     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------------------------------------- 0.0/12.8 MB 281.8 kB/s eta 0:00:46
     --------------------------------------- 0.1/12.8 MB 525.1 kB/s eta 0:00:25
      -------------------------------------- 0.2/12.8 MB 958.4 kB/s eta 0:00:14
     - -------------------------------------- 0.3/12.8 MB 1.2 MB/s eta 0:00:11
     - -------------------------------------- 0.5/12.8 MB 1.5 MB/s eta 0:00:09
     - -------------------------------------- 0.6/12.8 MB 1.8 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/12.8 MB 1.9 MB/s eta 0:00:07
     -- ------------------------------------- 0.9/12.8 MB 2.1 MB/s eta 0:00:06
     --- ------------------------------------ 1.0/12.8 MB 2.1 MB/s eta 0:00:06
     --- ------------------------------------ 1.2/12.8 MB 2.2 MB/s eta

C:\Users\rokha\anaconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\rokha\anaconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\rokha\anaconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [12]:
nlp = spacy.load("en_core_web_sm")

In [13]:
punct = string.punctuation

In [14]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [15]:
from spacy.lang.en.stop_words import STOP_WORDS

# Access the stop words for English
stopwords = list(STOP_WORDS)

# Now, you can use the stopwords list
print(stopwords)


['while', 'ourselves', '’ll', 'with', "'re", 'used', 'nowhere', 'still', 'once', 'yours', 'so', 'and', 'please', '‘m', 'eleven', 'anyway', 'should', 'almost', 'why', 'whatever', 'namely', 'onto', 'their', '’ve', 'whose', 'fifty', 'we', 'when', 'everything', 'using', 'but', 'say', 'meanwhile', 'thence', 'few', 'really', 'such', 'being', 'i', 'beside', 'whereas', 'much', 'its', 'not', 'elsewhere', 'am', 'by', 'than', 'be', 'whom', 'many', "'ve", "n't", 'whither', 'besides', 'moreover', 'against', 'through', 'can', 'became', '’re', 'something', 'next', 'the', 'becoming', 'above', 'since', 'latter', 'sometimes', 'three', 'until', 'just', 'any', 'too', 'everyone', 'own', 'does', 'wherein', 'never', 'eight', 'nothing', '‘ve', 'make', 'always', 'those', 'third', 'on', "'d", 'whereafter', '‘d', 'he', 'toward', 'behind', 'into', 'us', 'about', 'becomes', 'these', 'ca', 'amount', 'may', 'keep', "'ll", 'has', 'hundred', '’d', 'side', 'take', 'will', 'n’t', 'hence', 'unless', 'nine', 'ours', 'seem

In [22]:
def text_data_collection(sentence):
    doc = nlp(sentence)
    tokens = []
    for token in doc:
        if token.lemma_ !="-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp= token.lower
        tokens.append(temp)
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [23]:
text_data_collection("Hello all, it's a beautiful day outside there!")

['hello', 'beautiful', 'day', 'outside']

TFIDF
Vectorization

In [24]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [25]:
tfidf =TfidfVectorizer(tokenizer=text_data_collection)

In [26]:
classifier = LinearSVC()

Train the model

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
from sklearn.model_selection import train_test_split

# Assuming X and y are your data and labels
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [29]:
y_train.shape

(2198,)

In [30]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [31]:
print(X_train.shape)
print(y_train.shape)


(2198,)
(2198,)


In [32]:
clf.fit(X_train, y_train)

C:\Users\rokha\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
C:\Users\rokha\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_collection at 0x000001D6A377B380>)),
                ('clf', LinearSVC())])

In [33]:
y_pred = clf.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [35]:
confusion_matrix(y_test, y_pred)

array([[230,  55],
       [ 68, 197]], dtype=int64)

In [36]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.77      0.81      0.79       285\n           1       0.78      0.74      0.76       265\n\n    accuracy                           0.78       550\n   macro avg       0.78      0.78      0.78       550\nweighted avg       0.78      0.78      0.78       550\n'

In [37]:
accuracy_score(y_test, y_pred)

0.7763636363636364

In [38]:
clf.predict(['Wow, i am Learning Natural Language processing!'])
#output1 means its positive

array([1], dtype=int64)

In [39]:
clf.predict(['i hate Learning Natural Language processing!'])

array([0], dtype=int64)